version: '3'


services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: salvio/php-composer-dev
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /routes/index.php
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./code:/var/www/html
      - .config/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - .config/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - myproject-network

#Docker Networks
networks:
  myproject-network:
    driver: bridge

